[env]
TERM = "xterm-256color"

[window]
padding.x = 8
padding.y = 8
decorations = "Buttonless"
opacity = 0.95
blur = true
option_as_alt = "Both"
dynamic_title = false

[font]
size = 9
builtin_box_drawing = true
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { family = "JetBrainsMono NF", style = "bold" }
italic = { family = "JetBrainsMono NF", style = "italic" }
bold_italic = { family = "JetBrainsMono NF", style = "bold_italic" }

[general]
import = [
  "~/dotfiles/config/alacritty/themes/catppuccin-mocha.toml"
]
