# animations

# bezier
bezier = fluid, 0.05, 0.9, 0.1, 1.05
bezier = smoothOut, 0.36, 0, 0.66, -0.56
bezier = smoothIn, 0.25, 1, 0.5, 1
bezier = snappy, 0.05, 0.9, 0.1, 1.1
bezier = md3_decel, 0.05, 0.7, 0.1, 1
bezier = overshot, 0.05, 0.9, 0.1, 1.1
bezier = crazy, 0.68, -0.55, 0.265, 1.55
bezier = jiggle, 0.1, 1.1, 0.1, 1.1
bezier = linear, 1, 1, 1, 1

# animation speed
$speed_fast = 4
$speed_norm = 6
$speed_slow = 8

# selected
$active_speed = $speed_norm
$active_curve = fluid
$anim_style   = popin 70% # or slide, popin, gnomed

animations {
    enabled = yes
    # Window Open/Close
    animation = windows, 1, $active_speed, $active_curve, $anim_style
    animation = windowsOut, 1, $active_speed, $active_curve, $anim_style
    animation = windowsIn, 1, $active_speed, $active_curve, $anim_style
    animation = windowsMove, 1, $active_speed, $active_curve
    animation = workspaces, 1, $active_speed, $active_curve, slide
    animation = specialWorkspace, 1, $active_speed, $active_curve, slidefadevert

    animation = border, 1, 10, default
    animation = borderangle, 1, 30, linear, loop
    animation = fade, 1, $active_speed, default
}
