# Window rules

# General Defaults
windowrule {
    name = DefaultFloating
    match:class = ^()$
    float = on
    center = on
    size = (monitor_w*0.50) (monitor_h*0.50)
}

# Browser related
$browser = ^(firefox|librewolf|zen|zen-beta|chromium|brave-browser)$

windowrule {
    name = PictureInPicture
    match:class = $browser
    match:title = ^(Picture-in-Picture)$
    float = on
    move = (monitor_w-window_w-20) 20
    size = (monitor_w*0.40) (monitor_h*0.40)
}

windowrule {
    name = BrowserLibrary
    match:class = $browser
    match:title = ^(Library)$
    float = on
    center = on
    size = (monitor_w*0.60) (monitor_h*0.60)
}

windowrule {
    name = BrowserExtension
    match:class = $browser
    match:title = ^(Extension:)(.*)$
    float = on
    center = on
    size = (monitor_w*0.35) (monitor_h*0.65)
}

windowrule {
    name = FileDialogs
    match:class = ^(($browser)|(xdg-desktop-portal-gtk.*)|(.*Telegram.*))$
    match:title = ^((Opening)(.*)|(Open Files)|(All Files)|(Save.*))$
    float = on
    center = on
    size = (monitor_w*0.50) (monitor_h*0.50)
}


# System utils
windowrule {
    name = SystemTools
    match:class = ^((.*blueman-manager.*)|(.*pavucontrol.*)|(.*nm-applet.*)|(.*nm-connection-editor.*))$
    float = on
    center = on
    size = (monitor_w*0.40) (monitor_h*0.60)
    # gtk apps save window state to dconf & bypass windowrule
    suppress_event = maximize fullscreen
}

windowrule {
    name = GParted
    match:class = ^(GParted)$
    match:initial_title = ^(GParted)$
    float = on
    center = on
    size = (monitor_w*0.60) (monitor_h*0.60)
    suppress_event = maximize fullscreen
}

# Security
windowrule {
    name = Bitwarden
    match:class = ^(Bitwarden|firefox|zen|zen-beta|librewolf|chrome-.*)$
    match:initial_title = ^(Bitwarden|Extension.*|.*Firefox.*|_crx_.*)$

    float = on
    suppress_event = maximize
    no_screen_share = on

    move = (monitor_w-window_w-20) 20
    size = (monitor_w*0.30) (monitor_h*0.70)
}
windowrule {
    name = BitwardenApp
    match:class = ^(Bitwarden)$
    match:title = ^(Bitwarden)$

    float = on
    center = on
    suppress_event = maximize
    no_screen_share = on
    size = (monitor_w*0.30) (monitor_h*0.70)
}

# misc
windowrule {
    name = ProtonVPN
    match:class = ^(.*protonvpn.*)$
    float = on
    center = on
}

windowrule {
    name = MediaPlayers
    match:class = ^(.*mpv.*|.*imv.*|.*vlc.*)$
    float = on
    center = on
    size = (monitor_w*0.60) (monitor_h*0.60)
    suppress_event = maximize
}

windowrule {
    name = TelegramMedia
    match:class = ^(org.telegram.desktop)$
    match:title = ^(Media viewer)$
    float = on
    center = on
    size = (monitor_w*0.60) (monitor_h*0.60)
    suppress_event= fullscreen maximize
}

# Layer rules
layerrule {
    name = Bar
    match:namespace = ^(waybar)$
    blur = on
    ignore_alpha = 0
}

layerrule {
    name = Notifications
    match:namespace = ^(notifications)$
    blur = on
    ignore_alpha = 0
}

layerrule {
    name = Launcher
    match:namespace = ^(fuzzel|wofi|rofi)$
    blur = on
    ignore_alpha = 0
    animation = slide
}

layerrule {
    name = Logout
    match:namespace = ^(logout_dialog)$
    blur = on
    ignore_alpha = 0
    dim_around = on
    animation = fade
}
