# window rules
# windowrulev2 = float, center, size <50% <50%, class:^()$
windowrulev2 = float, center, size <60% <60%, class:^(firefox|librewolf|zen|zen-beta)$, title:^(Picture-in-Picture)$
windowrulev2 = float, center, size <60% <60%, class:^(firefox|librewolf|zen|zen-beta)$, title:^(Library)$
windowrulev2 = float, center, size <50% <50%, class:^(firefox|librewolf|zen|zen-beta)$, title:(Extension:)(.*)
windowrulev2 = float, center, size <30% <30%, class:^(firefox|librewolf|zen|zen-beta)$, title:(Opening)(.*)

windowrulev2 = float ,center, size 600 400, class:^(.*blueman-manager.*)$
windowrulev2 = float ,center, size 600 400, class:^(.*pavucontrol.*)$
windowrulev2 = float ,center, size 600 400, class:^((.*network-manager.*)|(.*nm-applet.*)|(.*nm-connection-editor.*))$
windowrulev2 = float ,center, size 400 400, class:^(.*protonvpn.*)$
windowrulev2 = float ,center, size <80% <80%, class:^(.*btop.*)$
windowrulev2 = float ,center, size <80% <80%, class:^(.*imv.*)$
windowrulev2 = float ,center, size <80% <80%, class:^(.*mpv.*)$

# layer rules
layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = blur, notifications
layerrule = ignorezero, notifications
layerrule = blur, logout_dialog
layerrule = ignorezero, logout_dialog
layerrule = dimaround, logout_dialog
layerrule = animation fade, logout_dialog
layerrule = blur, fuzzel
layerrule = animation slide, fuzzel
