name = "Fluxd"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba85b77fc6caee176c777a10d15a7e9ae10c91cc27f55ee11ffe2e17b302c039"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
