name = "Fluxd"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72e3f91df78f060aaa419df218189a840d6cc9c378064f95da4bb640db70b9c7"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
