# Gruvbox Dark

$bg_darkest = rgb(1d2021)
$bg_darkestAlpha = 1d2021

$bg_dark = rgb(282828)
$bg_darkAlpha = 282828

$bg_medium = rgb(3c3836)
$bg_mediumAlpha = 3c3836

$bg_light = rgb(504945)
$bg_lightAlpha = 504945

$fg_primary = rgb(fbf1c7)
$fg_primaryAlpha = fbf1c7

$fg_secondary = rgb(ebdbb2)
$fg_secondaryAlpha = ebdbb2

$fg_tertiary = rgb(d5c4a1)
$fg_tertiaryAlpha = d5c4a1

$fg_disabled = rgb(928374)
$fg_disabledAlpha = 928374

$accent_primary = rgb(8ec07c)
$accent_primaryAlpha = 8ec07c

$accent_secondary = rgb(83a598)
$accent_secondaryAlpha = 83a598

$accent_info = rgb(fabd2f)
$accent_infoAlpha = fabd2f

$accent_success = rgb(b8bb26)
$accent_successAlpha = b8bb26

$accent_warning = rgb(fe8019)
$accent_warningAlpha = fe8019

$accent_error = rgb(fb4934)
$accent_errorAlpha = fb4934

$accent_special = rgb(d3869b)
$accent_specialAlpha = d3869b
