name = "Flux"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55b7992486dd7d7a46177df0d27681ce3d6d96381c75e5a6065a116ad062e1de"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
