name = "Flux"
author = "git404x"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de8a9f95e04db4fb316fa0f5e4892742814e854631d42a4d21326b36b7dee401"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
